camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Anna
    lastName: Konda
  filter:
    create: All tasks

spring:
  datasource:
    url: jdbc:postgresql://localhost/camunda
    username: camunda
    password: camunda
  profiles:
    active: ${ENVIRONEMENT:local}