spring:
  application:
    name: simple-service

security:
  oauth2:
    client:
      clientId: simple-service
      clientSecret: "c6f809ba-5196-44e2-8fad-cd7249abbe90"
    resource:
      tokenInfoUri: http://192.168.99.100:30111/auth/realms/minikube/protocol/openid-connect/token/introspect