# Environment variables to be set:
#
# AUTHSERVER_CLIENTID: clientId
# AUTHSERVER_BASEURL: keycloak base url (e.g. https://auth.mydomain.com)
# AUTHSERVER_CLIENTSECRET: OIDC client_secret for this client

spring:
  application:
    name: simple-service

security:
  oauth2:
    client:
      clientId: ${authserver.client-id} 
      clientSecret: ${authserver.client-secret}
    resource:
      tokenInfoUri: ${authserver.base-url}/auth/realms/demo/protocol/openid-connect/token/introspect