apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: s3fs
  labels:
    app: s3fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3fs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: s3fs
        tier: storage
    spec:
      containers:
      - name: s3fs
        image: roskenet/s3fs:1.0.0
        securityContext:
          privileged: true
          # capabilities:
          #   add:
          #     - SYS_ADMIN
          #     - MKNOD
        env:
        - name: DUMB_INIT_VER
          value: 1.2.0
        - name: S3_BUCKET
          value: storage.roskenet.de
        - name: S3_REGION
          value: eu-central-1
        - name: MNT_POINT
          value: /data/storage
        - name: AWS_KEY
          value: <aws_key>
        - name: AWS_SECRET_KEY
          value: <aws_secret_key>
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
