apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oxygen
  namespace: oxygen
spec:
  rules:
  - host: oxygen.playground
    http:
      paths:
        - backend:
            serviceName: oxygen
            servicePort: 8080
