apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: chemicals
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

