kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
