kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol02
  namespace: development
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol02"
