apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakadi-deployment
  labels:
    app: nakadi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nakadi
  template:
    metadata:
      labels:
        app: nakadi
    spec:
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      - name: zookeeper-1
        persistentVolumeClaim:
          claimName: zookeeper-pv-claim-1
      - name: zookeeper-2
        persistentVolumeClaim:
          claimName: zookeeper-pv-claim-2
      - name: kafka-1
        persistentVolumeClaim:
          claimName: kafka-pv-claim-1
      - name: kafka-2
        persistentVolumeClaim:
          claimName: kafka-pv-claim-2
      containers:
      - name: postgres
        image: roskenet/nakadidb:1.0.0
        env:
        - name: POSTGRES_USER
          value: nakadi
        - name: POSTGRES_PASSWORD 
          value: nakadi
        - name: POSTGRES_DB
          value: local_nakadi_db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      - name: zookeeper
        image: zookeeper:3.6
        env:
        - name: ZOO_ADMINSERVER_ENABLED
          value: "false"
        volumeMounts:
        - mountPath: /data
          name: zookeeper-1
        - mountPath: /datalog
          name: zookeeper-2
      - name: kafka
        image: bitnami/kafka:3.6
        env:
        - name: BITNAMI_DEBUG
          value: "yes"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ENABLE_KRAFT
          value: "no"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "INTERNAL://localhost:9092,EXTERNAL://localhost:29092,CLIENT://localhost:9093"
        - name: KAFKA_CFG_LISTENERS
          value: "INTERNAL://localhost:9092,EXTERNAL://0.0.0.0:29092,CLIENT://:9093"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "localhost:2181"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_CLIENT_USERS
          value: "nakadi, producer"
        - name: KAFKA_CLIENT_PASSWORDS
          value: "nakadi_password, producer_password"
        - name: KAFKA_CFG_SASL_ENABLED_MECHANISMS
          value: "PLAIN"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-1
        - mountPath: /etc/kafka/secrets
          name: kafka-2
      - name: nakadi
        image: roskenet/nakadi:1.0.0
        env:
        - name: NAKADI_OAUTH2_MODE
          value: "OFF"
        - name: NAKADI_ZOOKEEPER_CONNECTIONSTRING
          value: "zookeeper://localhost:2181"
