apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqube
  namespace: coding
spec:
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:7.1-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: web
          containerPort: 9000
        - name: sonar
          containerPort: 9092
        env:
        - name: SONARQUBE_JDBC_USERNAME 
          value: sonarqube
        - name: SONARQUBE_JDBC_PASSWORD 
          value: sonarqube
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://postgresql.database/sonarqube
