apiVersion: v1
kind: Service
metadata:
  name: sonarqube-web
  namespace: coding
  labels:
    run: sonarqube-web
spec:
  selector:
    app: sonarqube
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30900
  type: NodePort
