apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeter
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: roskenet/greeter:0.0.2
        ports:
        - name: service
          containerPort: 8080
