apiVersion: v1
kind: Service
metadata:
  name: greeter
  labels:
    run: greeter
spec:
  selector:
    app: greeter
  ports:
  - port: 8080
    targetPort: service
    nodePort: 30100
  type: NodePort
