apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: roskenet/gateway:0.0.1
        ports:
        - name: service
          containerPort: 8080 
