apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    run: gatewayservice
spec:
  selector:
    app: gateway
  ports:
  - port: 8080
    name: service
    protocol: TCP
    nodePort: 30300
  type: NodePort
