apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://postgres/sonar
        - name: SONAR_JDBC_USERNAME
          value: sonar
        - name: SONAR_JDBC_PASSWORD
          value: sonar
        volumeMounts:
        - name: sonar-data
          mountPath: /opt/sonarqube/data
        - name: sonar-extensions
          mountPath: /opt/sonarqube/extensions
        - name: sonar-logs
          mountPath: /opt/sonarqube/logs
#        livenessProbe:
#          httpGet:
#            path: /api/system/status
#            port: 9000
#          initialDelaySeconds: 30
#          periodSeconds: 60
        ports:
        - name: web
          containerPort: 9000
      volumes:
      - name: sonar-data
        hostPath:
          path: /mnt/minikube/mounts/sonar/data
          type: Directory
      - name: sonar-extensions
        hostPath:
          path: /mnt/minikube/mounts/sonar/extensions
          type: Directory
      - name: sonar-logs
        hostPath:
          path: /mnt/minikube/mounts/sonar/logs
          type: Directory
