apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
  namespace: keycloak
spec:
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: keycloak-database
        context: keycloak
    spec:
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
      containers:
      - name: postgres
        image: postgres:11
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432 
        env:
        - name: POSTGRES_PASSWORD
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: database
