spring:
  datasource:
    url: jdbc:postgresql://localhost/nakadi_demo
    username: postgres
    password: postgres

fahrschein:
  defaults:
    nakadi-url: http://localhost:9090
    application-name: example-application
    consumer-group: example-consumergroup
    stream-parameters:
      batch-limit: 1000
      max-uncommitted-events: 5000
      batch-flush-timeout: 5
    oauth:
      enabled: false
      credentials-directory: /meta/credentials
    record-metrics: true
    http:
      content-encoding: gzip
    backoff:
      enabled: true
  consumers:
    orders:
      topics:
      - order.ORDER_RECEIVED'
      stream-parameters:
        batch-limit: 5
        max-uncommitted-events: 20
      backoff:
        enabled: false