spring:
  application:
    name: configury

  cloud:
    config:
      server:
        git:
          uri: https://github.com/roskenet/config
          search-paths:
          - helloworld
          - gateway