version: "3"

services:

  database:
    image: postgres:10.4
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data

  auth-service:
    image: jboss/keycloak:4.1.0.Final
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak

  simple-service:
    image: simple-service:0.0.1
    depends_on:
      - auth-service
    ports:
      - "8082:8082"

  simple-client:
    image: simple-client:0.0.1
    ports:
      - "8081:8081"
