version: "3"
networks:
  keycloak:

services:

  database:
    image: postgres:10.4
    networks:
      - keycloak
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:4.1.0.Final
    networks:
      - keycloak
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak

#  simple-service:
#    image: simple-service:0.0.1
#    networks:
#      - keycloak
#    depends_on:
#      - keycloak
#    ports:
#      - "8081:8080"
