apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template: 
    metadata:
      labels:
        app: keycloak
        context: keycloak
    spec:
      containers:
      - name: keycloak
        image: roskenet/keycloak:1.1.0
        args: ["start-dev"]
        ports:
        - name: service
          containerPort: 8080
          protocol: TCP
