apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template: 
    metadata:
      labels:
        app: keycloak
        context: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak/keycloak:latest
        args: ["start-dev", "--db-url=jdbc:postgresql://postgres:5432/keycloak", "--db=postgres", "--db-username=keycloak", "--db-password=keycloak"]
        env:
        - name: HOSTNAME
          value: keycloak.192-168-49-2.nip.io
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: password
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: keycloak
        - name: DB_PASSWORD
          value: keycloak
        - name: DB_DATABASE
          value: keycloak
        ports:
        - name: service
          containerPort: 8080
          protocol: TCP
