kind: PersistentVolume
apiVersion: v1
metadata:
  name: keycloak-database
  labels:
    type: local
    context: keycloak
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol001"
