apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    run: keycloak
    context: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    name: service
    protocol: TCP
    nodePort: 30111
  type: NodePort
