apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: roskenet/frontend:0.0.1
        ports:
        - name: service
          containerPort: 8080 
