kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database
  namespace: keycloak
  labels:
    context: keycloak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
