CREATE TABLE ordered_article (
	id SERIAL PRIMARY KEY,
	order_date DATE NOT NULL,
	sku VARCHAR(30) NOT NULL,
	ql VARCHAR(30),
	ean VARCHAR(30),
	order_name TEXT,
	format TEXT,
	island TEXT,
	production_type TEXT,
	order_type TEXT,
	production_location TEXT,
	origin_warehouse TEXT,
	order_number TEXT,
	sorting_location TEXT,
	season TEXT,
	commodity_group TEXT,
	sport_type TEXT,
	expected_inbound_date DATE NOT NULL,
	inbounded BOOLEAN,
	inbound_timestamp TIMESTAMP
);

CREATE TABLE inbounded_article (
	id SERIAL PRIMARY KEY,
	inbound_timestamp TIMESTAMP NOT NULL,
	sku VARCHAR(30),
	ql VARCHAR(30) NOT NULL,
	ean VARCHAR(30) NOT NULL,
	order_name TEXT,
	format TEXT,
	island TEXT,
	production_type TEXT,
	order_type TEXT,
	production_location TEXT,
	origin_warehouse TEXT,
	order_number TEXT,
	sorting_location TEXT,
	user_id VARCHAR(50),
	season TEXT,
	commodity_group TEXT,
	sport_type TEXT,
	is_ordered BOOLEAN
);
