kind: PersistentVolume
apiVersion: v1
metadata:
  name: datavol03
  namespace: tick
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol03"
