apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: tick
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: influxdb-claim
      containers:
      - name: influxdb
        image: influxdb:1.5.1
        ports:
        - name: service
          containerPort: 8086
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: data
