kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ldap
  namespace: management
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
