kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ldap-data
  namespace: development
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
