packloadall " Load all plugins
silent! helptags ALL

nmap <F2> :NERDTreeToggle<CR>

set autochdir
set nocompatible
set clipboard=unnamed,unnamedplus

filetype indent plugin on
syntax on

set laststatus=2

" Load powerline
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup


set number

" set showcmd

set shiftwidth=4
set softtabstop=4
set expandtab

set guicursor+=a:blinkon0

if &term =~ "xterm\\|rxvt"
  " use an orange cursor in insert mode
  let &t_SI = "\<Esc>]12;orange\x7"
  " use a red cursor otherwise
  let &t_EI = "\<Esc>]12;red\x7"
  silent !echo -ne "\033]12;red\007"
  " reset cursor when vim exits
  autocmd VimLeave * silent !echo -ne "\033]112\007"
  " use \003]12;gray\007 for gnome-terminal and rxvt up to version 9.21
endif

" Set up persistent undo across all files.
set undofile
if !isdirectory(expand("$HOME/.vim/undodir"))
  call mkdir(expand("$HOME/.vim/undodir"), "p")
endif
set undodir=$HOME/.vim/undodir

" Set up global swap dir.
set directory=$HOME/.vim/swap//

