apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxygen
  template:
    metadata:
      labels:
        app: oxygen
    spec:
      containers:
      - name: oxygen
        image: roskenet/oxygen:0.4.0
        ports:
        - name: api
          containerPort: 8080
