apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: runtime-config
  labels:
    run: dicovery
spec:
  selector:
    app: discovery
  ports:
  - port: 8761
    targetPort: eureka
    protocol: TCP
