apiVersion: v1
kind: Service
metadata:
  name: hydrogen-service
  namespace: hydrogen
  labels:
    app: hydrogen
spec:
  selector:
    app: hydrogen-server
  ports:
  - port: 8080
    nodePort: 30111
    protocol: TCP
  type: NodePort
