apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
  labels:
    application: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
    protocol: TCP
