apiVersion: v1
kind: Service
metadata:
  name: actinium
  labels:
    project: alchemy
    app: actinium
  annotations:
    maintainer: "felix@roskenet.de"
spec:
  selector:
    app: actinium
#  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
