kind: PersistentVolume
apiVersion: v1
metadata:
  name: {VOLUME}
  labels:
    type: minikube
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/{VOLUME}"
