spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.99.100:30111/auth/realms/Demo-Realm

management:
  server:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8000

logging:
  level:
    root: INFO
    #org.springframework: INFO
    #org.springframework.boot.actuate.endpoint.mvc: WARN
    #org.springframework.web.servlet.handler: WARN
    org.springframework.security: DEBUG