apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template: 
    metadata:
      labels:
        app: keycloak
        context: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak/keycloak:latest
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: password
        ports:
        - name: service
          containerPort: 8080
          protocol: TCP
