apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery
  namespace: runtime-config
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: discovery
    spec:
      containers:
      - name: discovery
        image: roskenet/discovery:1.5.3
        ports:
        - name: eureka
          containerPort: 8761
