all: postgres keycloak camunda

postgres:
	echo "Here we deploy postgres on minikube"
keycloak:
	echo "Here we deploy keycloak on minikube"
camunda:
	echo "Here we deploy camunda on minikube"

clean:
	echo "Here we clean up if needed"
