# Example of how a local configuration would look like
# when using keycloak on localhost:8080
authserver:
  base-url: http://localhost:8080
  client-id: simple-service
  client-secret: "3a626d59-1eed-411f-bc5e-e3dc3f625784"

server:
  port: 8091