# Environment variables to be set:
#
# AUTHSERVER_CLIENTID: clientId
# AUTHSERVER_BASEURL: keycloak base url (e.g. https://auth.mydomain.com)
# AUTHSERVER_CLIENTSECRET: OIDC client_secret for this client
authserver:
  base-url: http://192.168.99.100:30111/
  client-id: tutorial-backend
  client-secret: "e41b649e-54d0-43b4-b01a-4df56247220d"

server:
  port: 8000
#  port: 8091
  
spring:
  application:
    name: simple-service

security:
  oauth2:
    client:
      clientId: ${authserver.client-id} 
      clientSecret: ${authserver.client-secret}
    resource:
      tokenInfoUri: ${authserver.base-url}/auth/realms/Demo-Realm/protocol/openid-connect/token/introspect