apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    run: helloworld
spec:
  selector:
    app: helloworld
  ports:
  - port: 8080
    name: service
    protocol: TCP
    nodePort: 30100
  type: NodePort
