apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discoverydeployment
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: discovery
    spec:
      containers:
      - name: admin
        image: roskenet/discovery:1.0.0
        ports:
        - containerPort: 8761
