apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: elk
    spec:
      containers:
      - name: elk
        image: sebp/elk
        ports:
        - name: svca
          containerPort: 5601
          protocol: TCP
        - name: svcb
          containerPort: 9200
          protocol: TCP
        - name: svcc
          containerPort: 5044
          protocol: TCP
