kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgres"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-pv-volume-1
  labels:
    type: local
    app: zookeeper
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/zookeeper_1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-pv-volume-2
  labels:
    type: local
    app: zookeeper
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/zookeeper_2"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-volume-1
  labels:
    type: local
    app: kafka
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/kafka_1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-volume-2
  labels:
    type: local
    app: kafka
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/kafka_2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  volumeName: postgres-pv-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-pv-claim-1
  labels:
    app: zookeeper
spec:
  storageClassName: manual
  volumeName: zookeeper-pv-volume-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-pv-claim-2
  labels:
    app: zookeeper
spec:
  storageClassName: manual
  volumeName: zookeeper-pv-volume-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-pv-claim-1
  labels:
    app: kafka
spec:
  storageClassName: manual
  volumeName: kafka-pv-volume-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-pv-claim-2
  labels:
    app: kafka
spec:
  storageClassName: manual
  volumeName: kafka-pv-volume-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
