apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworlddeployment
spec:
  replicas: 3
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: roskenet/helloworld:1.1.0
        ports:
        - name: service
          containerPort: 8080 
        - name: management
          containerPort: 7979
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
