apiVersion: v1
kind: Service
metadata:
  name: helloworldservice
  labels:
    run: helloworldservice
spec:
  selector:
    app: helloworld
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30010
  type: NodePort
