version: "3"

services:

  database:
    image: postgres:10.4
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data

  auth-service:
    image: jboss/keycloak:4.1.0.Final
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak

  simple-service:
    image: roskenet/simple-service:1.0.0
    ports:
      - "8082:8080"
    environment:
      - AUTHSERVER_CLIENTID=simple-service
      - AUTHSERVER_CLIENTSECRET=3a626d59-1eed-411f-bc5e-e3dc3f625784
      - AUTHSERVER_BASEURL=http://auth-service:8080

  simple-client:
    image: roskenet/simple-client:1.0.0
    ports:
      - "8081:8080"
    environment:
      - AUTHSERVER_CLIENTID=simple-client
      - AUTHSERVER_CLIENTSECRET=c0dba145-1cce-4775-be90-5909094bb361
      - AUTHSERVER_BASEURL=http://auth-service:8080
      - SIMPLESERVICE_URL=http://simple-service:8080
