apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configury
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: configury
    spec:
      containers:
      - name: configury
        image: roskenet/configury:1.2.0
        ports:
        - containerPort: 8080
