kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
