site_name: Flx'ProgrammingSteps

theme:
  name: material
  features: 
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
