apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chronograf-depl
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:1.4.3.1
        ports:
        - name: service
          containerPort: 8888
        env:
        - name: INFLUXDB_URL
          value: http://influxdb-svc.default.svc.cluster.local:8086
        - name: KAPACITOR_URL
          value: http://kapacitor-svc.default.svc.cluster.local:9092
