kind: PersistentVolume
apiVersion: v1
metadata:
  name: database
  labels:
    type: local
    path: database
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/database"
