apiVersion: v1
kind: Pod
metadata:
  name: servicepod
  labels:
    app: servicepod
spec:
  containers:
  - image: roskenet/servicepod:1.0.1
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: servicepod
  restartPolicy: Always

