apiVersion: v1
kind: Service
metadata:
  name: adminservice
  labels:
    run: adminservice
spec:
  selector:
    app: admin
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30100
  type: NodePort
