spring:
  application:
    name: "@project.artifactId@"

server:
  port: 8081

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: "c0dba145-1cce-4775-be90-5909094bb361"
      access-token-uri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
      grant-type: client_credentials
      scope:
        - profile
        - offline_access
