# Environment variables to be set:
#
# AUTHSERVER_CLIENTID: clientId
# AUTHSERVER_BASEURL: keycloak base url (e.g. https://auth.mydomain.com)
# AUTHSERVER_CLIENTSECRET: OIDC client_secret for this client
# SIMPLESERVICE_URL: Go figure! URL of simple-service

spring:
  application:
    name: simple-client

security:
  oauth2:
    client:
      client-id: ${authserver.client-id}
      client-secret: ${authserver.client-secret}
      access-token-uri: ${authserver.base-url}/auth/realms/demo/protocol/openid-connect/token
      grant-type: client_credentials
      scope:
        - profile
        - offline_access
