apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb-depl
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.5.1
        ports:
        - name: service
          containerPort: 8086
