apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  template: 
    metadata:
      labels:
        application: postgres
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres
      containers:
      - name: postgres
        image: postgres:11
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432 
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: data
