site_name: "Felix' Bookshelf"
site_author: "Felix Roske"
site_url: "http://www.felixroske.de/"

theme:
  name: "material"
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - attr_list
  - smarty
  - extra
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - footnotes

extra:
  social:
    - type: "github"
      link: "https://github.com/roskenet"
    - type: "twitter"
      link: "https://twitter.com/felixroske"
    - type: "facebook"
      link: "https://www.facebook.com/felix.roske"

