# Format documented at:
# https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
#
# Not used in this project for now!
#
version: 1
disable_existing_loggers: true

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout  # https://12factor.net/logs

root:
  level: DEBUG
  handlers:
    - console

