apiVersion: v1
kind: Service
metadata:
  name: nakadi
spec:
  selector:
    app: nakadi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
    name: api
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: ui
